version: '2'

services:
  dns:
    build: dns
    hostname: dns
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - local

  zookeeper:
    build: zookeeper
    hostname: zookeeper
    networks:
      - local

  hdfsnamenode:
    build: hdfs-namenode
    hostname: hdfsnamenode
    volumes:
      - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
    networks:
      - local

  yarnresourcemanager:
    build: yarn-resource-manager
    volumes:
      - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
    hostname: yarnresourcemanager
    networks:
      - local

  mapreducehistory:
    build: mapreduce-history
    hostname: mapreducehistory
    volumes:
      - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
    networks:
      - local

  clusternode:
    build: cluster-node
    domainname: cdh5-local
    volumes:
      - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
    networks:
      - local

  hiveserver:
    build: hive-server
    volumes:
      - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
    hostname: hiveserver
    networks:
      - local

  hivemetastore:
     environment:
           POSTGRES_VERSION: 9.5
           PGPASSWORD: elephants
     hostname: hivemetastore
     build: hive-metastore
     volumes:
       - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
     networks:
       - local

  postgres:
     build: postgres
     hostname: postgres
     environment:
           POSTGRES_USER: root
           POSTGRES_PASSWORD: elephants
           POSTGRES_DB: root
     ports:
       - "5000:5432"
     networks:
       - local

  hue:
     build: hue
     volumes:
       - "./conf/cluster-conf:/etc/hadoop/cluster-conf:ro"
       - "./conf/conf.hue:/etc/hue/conf:ro"
     networks:
       - local

networks:
  local:
    external:
      name: cdh5-local
